version: "3"
services:
  campaign-consumer-api-db:
    image: campaign-consumer-api-db
    container_name: campaign-consumer-api-db
    ports:
      - "5432:5432"
    build: 
      context: .
      args:
        - LOCAL_SQL=./database/squemas
        - MIGRATIONS_SQL=./database/tables
      dockerfile: ./database/Dockerfile