version: "3.9"
services:
  app:
    build:
      context: ./database
      dockerfile: dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432 