FROM postgres:14

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=consumer-campaing-pg

EXPOSE 5432:5432

ARG LOCAL_SQL=squemas
ARG MIGRATIONS_SQL=tables

COPY $LOCAL_SQL /docker-entrypoint-initdb.d/
COPY $MIGRATIONS_SQL /docker-entrypoint-initdb.d/
EXPOSE 5432:5432